### ISSUE TITLE
emacs irony nixos

### ISSUE THREAD

**Issue by nico202** [acowley/dotfiles#1]
Hi, I wanted to contact you privately but don't know if it's possible on github. Does irony works with your configuration.nix? I see that you added the irony-server nix package, so I think it does work, but I don't have time to waste if it does not work XD
Thanks (and thank you for sharing your dotfiles)

**Comment by acowley** [comment]
Yes, it work(ed), but it took a fair bit of fiddling to get it right. The tricky part is that irony-server needs the clang flags that nix would use. I will dig up how I did this when I have a minute and add it here.

**Comment by acowley** [comment]
I think things are still working for me, actually. I have a [fork](https://github.com/acowley/irony-mode) of `irony-mode` that provides `irony-parse` and `irony-diagnostics` interactive functions that can be helpful to figure out what the server is doing.

In any case, I just tried it out again with a dummy project, and things seemed to work. One thing I noticed, though, is that I have the `irony-server` executable installed with `nix-env` so it's available at a fixed location. I never sorted out a proper way of having `irony-mode` pick it up from `nix-shell`. A risk this causes is getting versions of `clang` confused. To get things working just now, I had to re-install `irony-server` with `nix-env` to make sure it was built with the same `clang` I was using in the `nix-shell` for my dummy project.

Getting it to pick up the right `irony-server` from a `shell.nix` would be useful. I usually use a `.dir-locals.el` for that.

**Comment by acowley** [comment]
Hey @nico202, were you able to make any progress on this? Just today I started a new project using `irony-server` and OpenGL and OpenCL, and everything is working fine. I did have to create a `.clang-complete` file to get all the includes.

**Comment by nico202** [comment]
Trying out right now, I'll update here

**Comment by nico202** [comment]
Done, thanks! I'm posting the code I'm using:
configuration.nix
```let
  custom_irony_server = with pkgs;
      stdenv.mkDerivation {
      name = "irony-server-2016-08-24";
        src = fetchFromGitHub {
        owner = "Sarcasm";
        repo = "irony-mode";
        rev = "11bdf09b998c54be59bac8df3368039de2c0aa19";
        sha256 = "1q0liagda4ch9ya5ic9flwprxv4wq23ws3kg00d4wg0y3x4czwhm";
      };
      buildInputs = [ cmake llvm llvmPackages.clang-unwrapped];
      preConfigure = "cd server";
      };
```
the custom_irony_server variable is added to the systemPackages

then in init.el, the relevant part is the line:

>       (setq irony-server-install-prefix "/run/current-system/sw/")

(since company is installed system-wide)

it seems to be working, i get completition with company (irony-mode is installed with emacs24PackagesNg.irony)

Thanks!

**Comment by nico202** [comment]
Just for future reference, now irony-server is provided by the nixpkgs repository and is already the same version as the melpa package
